import { Button, VerticalBox } from "std-widgets.slint";

export component App inherits Window {

    width: 600px;
    height: 800px;

    out property<int> choice;
    callback send_data(int, string, string);

    property<string> name;
    property<string> surname;
    property<string> street;
    property<string> city;

    in property<[string]> people;
    in property<[string]> addresses;

    VerticalLayout {
        Button {
            text: "Person";
            clicked => { choice = 1;  }
        }
        Button {
            text: "Address";
            clicked => { choice = 2; }
        }
        Button {
            text: "List";
            clicked => { 
                choice = 3;
            }
        }
        
        if choice == 1 : personInput := VerticalLayout {
            Text {text: "Name";}
            TextInput { 
                text: name; 
                edited => {name = self.text}
            }
            Text {text: "Surname";}
            TextInput { 
                text: surname;
                edited => {surname = self.text}
            }
            Button {
                text: "Send";
                clicked => { 
                    root.send_data(1, name, surname); 
                    choice = 0;
                    street = "";
                    city = "";
                    name = "";
                    surname = "";
                    
                }
            }
        }
        if choice == 2: addressInput := VerticalLayout {
            Text {text: "Street";}
            TextInput { 
                text: street; 
                edited => {street = self.text}
            }
            Text {text: "City";}
            TextInput { 
                text: city;
                edited => {city = self.text}
            }
            Button {
                text: "Send";
                clicked => { 
                    root.send_data(2, street, city);
                    choice = 0;
                    street = "";
                    city = "";
                    name = "";
                    surname = ""; 
                }
            }
        }
        if choice == 3: listall := VerticalLayout{
            for person[i] in people: HorizontalLayout{
                Text {
                    text: person;
                }
            }
            for addr[i] in addresses: HorizontalLayout{
                Text {
                    text: addr;
                }
            }
        }
    }
}

