[package]
name = "machine"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rand = "0.9.1"
reqwest = { version = "0.12.15", features = ["json"]}
serde = "1.0.219"
serde_json = "1.0.140"
sysinfo = "0.34.2"
tokio = { version = "1.44.1" , features = ["full"] }
